
CHANNEL_TYPE = "channel_type"
TYPE = "type"
RAW_CONTENT = "raw_content"
NICKNAME = "nickname"
K_MARKDOWN = "kmarkdown"
EXTRA = "extra"
AUTHOR_ID = "author_id"
CONTENT = "content"
AUTHOR = "author"
CHANNEL_NAME = "channel_name"